const GITHUB_AUTH_TOKEN = "null"
const BOT_NUMBER = "null"
const SESSION_ID = "PRABATH-MD~47VBDajZ#5qdAEZTXqEqRt6-7G1K3KMXFdG63UqtgXVn5r6XyY6E"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
